image: node:6.9.4
pipelines:
  branches:
    master:
      - step:
          script:
            - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            - npm i -D
            - npm run build
            - npm publish
